name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # run midnight
  workflow_dispatch:

jobs:
  sync:
    name: Sync Upstream
    runs-on: ubuntu-latest
    permissions:
      contents: write # push changes back to repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
         ref: main
         fetch-depth: 0 # fetch all histroy

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/CSA-Admin-OCS/pages.git
          git fetch upstream
# change to merge main
      - name: Merge Upstream
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream changes"          

      - name: Push Changes
        run: |
          git push origin HEAD:main
